version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:10.16

    steps:
      - run:
          name: Authenticate with registry
          command: |
            echo "@melio:registry=https://npm.pkg.github.com/melio" > ~/.npmrc
            echo "//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}" >> ~/.npmrc

      - checkout

      - restore_cache:
          key: v1-all-{{ checksum "package-lock.json" }}

      - run:
          name: Install dependencies
          command: npm install

      - save_cache:
          key: v1-all-{{ checksum "package-lock.json" }}
          paths: node_modules

      - run:
          name: Test
          command: npm run test

  publish:
    docker:
      - image: circleci/node:8.10

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Authenticate with registry
          command: |
            echo "@melio:registry=https://npm.pkg.github.com/melio" > ~/.npmrc
            echo "//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}" >> ~/.npmrc

      - run:
          name: Install production dependencies
          command: npm install --production

      - run:
          name: Publishing to npm
          command: npm publish

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - test:
          context: melio-all
          filters: # required since `publish` has tag filters AND requires `test`
            tags:
              only: /.*/
      - publish:
          requires:
            - test
          context: melio-all
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/